sudo: required

services:
    - docker

before_install:
    - docker build -t hoangvypfiev/docker-react -f Dockerfile.dev . 
    
script:
    - docker run hoangvypfiev/docker-react npm run test -- --coverage